name: DayZ Mod Update Checker

on:
  schedule:
    - cron: '0 * * * *'  # Setiap jam
  workflow_dispatch: # Manual trigger

jobs:
  check-mods:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests
    
    - name: Check for mod updates
      env:
        STEAM_API_KEY: ${{ secrets.STEAM_API_KEY }}
        DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
      run: python mod_notifier.py --once
